name: Add contributors to readme

on: [push, pull_request, workflow_dispatch]

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Add contributors to readme
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
